// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// EnableLogExportRequest struct for EnableLogExportRequest.
type EnableLogExportRequest struct {
	AuthPrincipal *string `json:"auth_principal,omitempty"`
	// aws_external_id to include when assuming the IAM role specified by role_arn. Optional. A specific value may be required by the role's trust policy. Only supported for Advanced clusters on AWS. If provided for a Standard cluster, the request is rejected.
	AwsExternalId *string `json:"aws_external_id,omitempty"`
	// Azure client ID for the app registration used by the Logs Ingestion API.
	AzureClientId *string `json:"azure_client_id,omitempty"`
	// Azure client secret for the app registration used by the Logs Ingestion API.
	AzureClientSecret *string `json:"azure_client_secret,omitempty"`
	// Logs ingestion endpoint of the Azure Data Collection Endpoint (DCE).
	AzureDceEndpoint *string `json:"azure_dce_endpoint,omitempty"`
	// Immutable ID of the Azure Data Collection Rule (DCR), for example dcr-...
	AzureDcrImmutableId *string `json:"azure_dcr_immutable_id,omitempty"`
	// Full ARM resource ID of the Azure Data Collection Rule (DCR). Cockroach Cloud reads and updates this DCR to add streams for each configured log group.
	AzureDcrResourceId *string `json:"azure_dcr_resource_id,omitempty"`
	// The primary or the secondary connected sources client authentication key. This is used to export logs to Azure Log Analytics via the legacy HTTP Data Collector API. Deprecated: use azure_client_secret instead.
	AzureSharedKey *string `json:"azure_shared_key,omitempty"`
	// Azure tenant ID for the app registration used by the Logs Ingestion API.
	AzureTenantId *string `json:"azure_tenant_id,omitempty"`
	// Full ARM resource ID of the Log Analytics workspace. Cockroach Cloud creates or updates the required custom tables for each configured log group.
	AzureWorkspaceResourceId *string `json:"azure_workspace_resource_id,omitempty"`
	// groups is a collection of log group configurations that allows the customer to define collections of CRDB log channels that are aggregated separately at the target sink.
	Groups *[]LogExportGroup `json:"groups,omitempty"`
	// log_name is an identifier for the logs in the customer's log sink.
	LogName string `json:"log_name"`
	// omitted_channels is a list of channels that the user does not want to export logs for.
	OmittedChannels *[]string `json:"omitted_channels,omitempty"`
	// redact allows the customer to set a default redaction policy for logs before they are exported to the target sink. If a group config omits a redact flag and this one is set to `true`, then that group will receive redacted logs.
	Redact *bool `json:"redact,omitempty"`
	// region allows the customer to override the destination region for all logs for a cluster.
	Region *string       `json:"region,omitempty"`
	Type   LogExportType `json:"type"`
}

// NewEnableLogExportRequest instantiates a new EnableLogExportRequest object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableLogExportRequest(logName string, type_ LogExportType) *EnableLogExportRequest {
	p := EnableLogExportRequest{}
	p.LogName = logName
	p.Type = type_
	return &p
}

// NewEnableLogExportRequestWithDefaults instantiates a new EnableLogExportRequest object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableLogExportRequestWithDefaults() *EnableLogExportRequest {
	p := EnableLogExportRequest{}
	return &p
}

// GetAuthPrincipal returns the AuthPrincipal field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAuthPrincipal() string {
	if o == nil || o.AuthPrincipal == nil {
		var ret string
		return ret
	}
	return *o.AuthPrincipal
}

// SetAuthPrincipal gets a reference to the given string and assigns it to the AuthPrincipal field.
func (o *EnableLogExportRequest) SetAuthPrincipal(v string) {
	o.AuthPrincipal = &v
}

// GetAwsExternalId returns the AwsExternalId field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAwsExternalId() string {
	if o == nil || o.AwsExternalId == nil {
		var ret string
		return ret
	}
	return *o.AwsExternalId
}

// SetAwsExternalId gets a reference to the given string and assigns it to the AwsExternalId field.
func (o *EnableLogExportRequest) SetAwsExternalId(v string) {
	o.AwsExternalId = &v
}

// GetAzureClientId returns the AzureClientId field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAzureClientId() string {
	if o == nil || o.AzureClientId == nil {
		var ret string
		return ret
	}
	return *o.AzureClientId
}

// SetAzureClientId gets a reference to the given string and assigns it to the AzureClientId field.
func (o *EnableLogExportRequest) SetAzureClientId(v string) {
	o.AzureClientId = &v
}

// GetAzureClientSecret returns the AzureClientSecret field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAzureClientSecret() string {
	if o == nil || o.AzureClientSecret == nil {
		var ret string
		return ret
	}
	return *o.AzureClientSecret
}

// SetAzureClientSecret gets a reference to the given string and assigns it to the AzureClientSecret field.
func (o *EnableLogExportRequest) SetAzureClientSecret(v string) {
	o.AzureClientSecret = &v
}

// GetAzureDceEndpoint returns the AzureDceEndpoint field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAzureDceEndpoint() string {
	if o == nil || o.AzureDceEndpoint == nil {
		var ret string
		return ret
	}
	return *o.AzureDceEndpoint
}

// SetAzureDceEndpoint gets a reference to the given string and assigns it to the AzureDceEndpoint field.
func (o *EnableLogExportRequest) SetAzureDceEndpoint(v string) {
	o.AzureDceEndpoint = &v
}

// GetAzureDcrImmutableId returns the AzureDcrImmutableId field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAzureDcrImmutableId() string {
	if o == nil || o.AzureDcrImmutableId == nil {
		var ret string
		return ret
	}
	return *o.AzureDcrImmutableId
}

// SetAzureDcrImmutableId gets a reference to the given string and assigns it to the AzureDcrImmutableId field.
func (o *EnableLogExportRequest) SetAzureDcrImmutableId(v string) {
	o.AzureDcrImmutableId = &v
}

// GetAzureDcrResourceId returns the AzureDcrResourceId field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAzureDcrResourceId() string {
	if o == nil || o.AzureDcrResourceId == nil {
		var ret string
		return ret
	}
	return *o.AzureDcrResourceId
}

// SetAzureDcrResourceId gets a reference to the given string and assigns it to the AzureDcrResourceId field.
func (o *EnableLogExportRequest) SetAzureDcrResourceId(v string) {
	o.AzureDcrResourceId = &v
}

// GetAzureSharedKey returns the AzureSharedKey field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAzureSharedKey() string {
	if o == nil || o.AzureSharedKey == nil {
		var ret string
		return ret
	}
	return *o.AzureSharedKey
}

// SetAzureSharedKey gets a reference to the given string and assigns it to the AzureSharedKey field.
func (o *EnableLogExportRequest) SetAzureSharedKey(v string) {
	o.AzureSharedKey = &v
}

// GetAzureTenantId returns the AzureTenantId field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAzureTenantId() string {
	if o == nil || o.AzureTenantId == nil {
		var ret string
		return ret
	}
	return *o.AzureTenantId
}

// SetAzureTenantId gets a reference to the given string and assigns it to the AzureTenantId field.
func (o *EnableLogExportRequest) SetAzureTenantId(v string) {
	o.AzureTenantId = &v
}

// GetAzureWorkspaceResourceId returns the AzureWorkspaceResourceId field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetAzureWorkspaceResourceId() string {
	if o == nil || o.AzureWorkspaceResourceId == nil {
		var ret string
		return ret
	}
	return *o.AzureWorkspaceResourceId
}

// SetAzureWorkspaceResourceId gets a reference to the given string and assigns it to the AzureWorkspaceResourceId field.
func (o *EnableLogExportRequest) SetAzureWorkspaceResourceId(v string) {
	o.AzureWorkspaceResourceId = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetGroups() []LogExportGroup {
	if o == nil || o.Groups == nil {
		var ret []LogExportGroup
		return ret
	}
	return *o.Groups
}

// SetGroups gets a reference to the given []LogExportGroup and assigns it to the Groups field.
func (o *EnableLogExportRequest) SetGroups(v []LogExportGroup) {
	o.Groups = &v
}

// GetLogName returns the LogName field value.
func (o *EnableLogExportRequest) GetLogName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LogName
}

// SetLogName sets field value.
func (o *EnableLogExportRequest) SetLogName(v string) {
	o.LogName = v
}

// GetOmittedChannels returns the OmittedChannels field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetOmittedChannels() []string {
	if o == nil || o.OmittedChannels == nil {
		var ret []string
		return ret
	}
	return *o.OmittedChannels
}

// SetOmittedChannels gets a reference to the given []string and assigns it to the OmittedChannels field.
func (o *EnableLogExportRequest) SetOmittedChannels(v []string) {
	o.OmittedChannels = &v
}

// GetRedact returns the Redact field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetRedact() bool {
	if o == nil || o.Redact == nil {
		var ret bool
		return ret
	}
	return *o.Redact
}

// SetRedact gets a reference to the given bool and assigns it to the Redact field.
func (o *EnableLogExportRequest) SetRedact(v bool) {
	o.Redact = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *EnableLogExportRequest) GetRegion() string {
	if o == nil || o.Region == nil {
		var ret string
		return ret
	}
	return *o.Region
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *EnableLogExportRequest) SetRegion(v string) {
	o.Region = &v
}

// GetType returns the Type field value.
func (o *EnableLogExportRequest) GetType() LogExportType {
	if o == nil {
		var ret LogExportType
		return ret
	}

	return o.Type
}

// SetType sets field value.
func (o *EnableLogExportRequest) SetType(v LogExportType) {
	o.Type = v
}
